# Generated by Django 4.1.4 on 2023-01-14 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import musics.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/profie-images', validators=[musics.validators.image_size])),
                ('user_mode', models.CharField(choices=[('s', 'silver'), ('g', 'gold'), ('d', 'diamond')], default='s', max_length=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_upgraded', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_file', models.FileField(upload_to='media/songs', validators=[musics.validators.music_type, musics.validators.music_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='songs', to='musics.album')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musics.profile')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='musics.profile'),
        ),
    ]
