# Generated by Django 4.1.4 on 2023-01-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='-', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
