# Generated by Django 4.1.4 on 2023-01-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_alter_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='-', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='-', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
