# Generated by Django 4.1.4 on 2023-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_rename_name_album_title_album_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
